Use newer flake8 to run on ubuntu-focal Zuul
flake8 2.6.2 failed on ubuntu-focal zuul machines running python3.8
with the following error:
AttributeError: 'FlakesChecker' object has no attribute 'CONSTANT'

pylint failed with following error:
ERROR: InvocationError for command /home/zuul/src/opendev.org/starlingx/test/.tox/pylint/bin/pylint
--rcfile=pylint.rc automated-p

upgrade openstackdocstheme to 2.2.1 and update sphinx version
fix releasenotes to use python3

Change-Id: Ie5e11b44a3ff9695a6ec44eaf4a53baababc27ac
Signed-off-by: Yvonne Ding <yvonne.ding@windriver.com>
(cherry picked from commit d1e88a989e1429d2e51fe8438a9c75ad17abe4f7)