Modified the env using pytest==3.6.1 and pyyaml==5.4.1
Description: This changes is needed in order to fix a test failure
Error msg: TypeError: load() missing 1 required positional argument: 'Loader'

Story: N/A
Task: N/A

Signed-off-by: Alexandru <alexandru.dimofte@intel.com>
Change-Id: I4b2537bbb1969bac25ac36c4fa7d1e8b889b992e